apiVersion: v1
kind: Pod
metadata:
  name: browser-pod-$ACCOUNT_ID
  namespace: admin-browsers
  labels:
    app: browser-pod
spec:
  automountServiceAccountToken: false
  containers:
  - name: docker-vnc-xfce4
    args: ["$ACCOUNT_ID"]
    image: registry.localhost:5000/docker-vnc-xfce4:latest
    tty: true
    ports:
      - containerPort: 6080
        name: novnc
    volumeMounts:
    - mountPath: /home/user/tbot
      name: code
    - mountPath: /entrypoint.sh
      name: entrypoint
    - mountPath: /dev/shm
      name: dshm
    - name: log-volume
      mountPath: /var/log
    - name: screenshots
      mountPath: /var/screenshots
    - name: videos
      mountPath: /var/videos
    env:
      - name: LANG
        value: en_EN.UTF-8
      - name: DESKTOP_ENV
        value: xfce4
      - name: DESKTOP_SIZE
        value: "1920x1080"
  volumes:
  - name: log-volume
    hostPath:
      path: /home/bijan/tinderbot2/logs
  - name: videos
    hostPath:
      path: /home/bijan/tinderbot2/videos
  - name: screenshots
    hostPath:
      path: /home/bijan/tinderbot2/screenshots
  - name: code
    hostPath:
      path: /home/bijan/tinderbot2
  - name: entrypoint
    hostPath:
      path: /home/bijan/tinderbot2/entrypoint_browser.sh
  - name: dshm
    emptyDir:
      medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: browser-pod
  namespace: admin-browsers
spec:
  type: NodePort
  selector:
    app: browser-pod
  ports:
    - name:
      protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: 30000
  externalIPs:
    # - 127.0.0.1
    - 192.168.1.71
    # - 100.121.94.78
    # - 65.108.104.217
