---
apiVersion: v1
kind: Service
metadata:
  name: bot1
  namespace: $NAMESPACE
spec:
  type: NodePort
  selector:
    app: swipejob-$JOBID
  ports:
    - name:
      protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: $NODEPORT
  externalIPs:
    # - 100.121.94.78
    - 65.108.104.217
