apiVersion: v1
kind: Pod
metadata:
  name: swipejob
  labels:
    app: swipejob
spec:
  automountServiceAccountToken: false
  containers:
  - name: docker-vnc-xfce4
    image: registry.localhost:5000/docker-vnc-xfce4:latest
    securityContext:
      allowPrivilegeEscalation: true
    # imagePullPolicy: Never
    tty: true
    ports:
      - containerPort: 6080
        name: novnc
    volumeMounts:
    - mountPath: /home/user/tbot2
      name: code
    - mountPath: /dev/shm
      name: dshm
    env:
      - name: LANG
        value: en_EN.UTF-8
      - name: DESKTOP_ENV
        value: xfce4
      - name: DESKTOP_SIZE
        value: "1920x1080"
  restartPolicy: Never
  volumes:
  - name: code
    hostPath:
      path: /home/bijan/tinderbot2
  - name: dshm
    emptyDir:
      medium: Memory
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bot1
# spec:
#   type: NodePort
#   selector:
#     app: swipejob
#   ports:
#     - name:
#       protocol: TCP
#       port: 6080
#       targetPort: 6080
#       nodePort: 30000
#   externalIPs:
#     - 100.121.94.78
#     - 65.108.104.217
