default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # database: tinderbot_dev
  # adapter: postgresql
  # encoding: unicode
  # username: postgres
  # password: admin
  database: db861fhrd8h5eb
  adapter: postgresql
  encoding: unicode
  username: u2c3ghkcr3hm4k
  password: p1dd4a8050c7462a917923f3094860ec5ccc7b5c4047748dc9123ad18a9912f9e
  host: ec2-44-209-2-222.compute-1.amazonaws.com

test:
  <<: *default
  database: tinderbot_test

production:
  <<: *default
  database: db861fhrd8h5eb
  adapter: postgresql
  encoding: unicode
  username: u2c3ghkcr3hm4k
  password: p1dd4a8050c7462a917923f3094860ec5ccc7b5c4047748dc9123ad18a9912f9e
  host: ec2-44-209-2-222.compute-1.amazonaws.com
